// Harta · content data
// Recipes: whole food, Mediterranean-pattern, family friendly. No calorie counts by design.
// Ingredient sections: produce | pantry | fridge | fishmeat | frozen | bakery
// Tags: quick (<=25 min hands-on), batch (doubles well, freezes), fish, legume, veg (vegetarian),
//       chicken, romanian, oven (mostly hands-off), kidsafe (reliably kid friendly)

export const SECTIONS = [
  ["produce", "Fruit and veg"],
  ["fishmeat", "Fish and meat"],
  ["fridge", "Fridge and dairy"],
  ["pantry", "Pantry"],
  ["frozen", "Frozen"],
  ["bakery", "Bakery"],
];

export const RECIPES = [
  {
    id: "sheetpan-salmon", name: "Tray-baked salmon with potatoes and broccolini", time: 15, total: 35,
    serves: 4, tags: ["fish", "oven", "kidsafe", "nosugar"],
    macros: { kcal: 580, protein: 37, fat: 30, carbs: 35, sugars: 3, fibre: 7 },
    ingredients: [
      { n: "Salmon fillets", q: "4", s: "fishmeat" },
      { n: "Baby potatoes", q: "800 g", s: "produce" },
      { n: "Broccolini", q: "2 bunches", s: "produce" },
      { n: "Lemon", q: "1", s: "produce" },
      { n: "Olive oil", q: "3 tbsp", s: "pantry", pantry: true },
      { n: "Garlic", q: "3 cloves", s: "produce" },
    ],
    method: [
      "Heat the oven to 200°C. Halve the potatoes, toss with oil and salt, roast 15 minutes.",
      "Add broccolini and garlic to the tray. Nestle in the salmon, skin down. Squeeze over half the lemon.",
      "Roast 12 to 14 minutes until the salmon just flakes. Serve with the rest of the lemon.",
    ],
    why: "Oily fish once or twice a week is one of the most consistent findings in heart-health research, and the omega-3s matter across the lifespan.",
    whySource: "Heart Foundation (Australia); Australian Dietary Guidelines",
    kidNote: "Serve the salmon flaked, with the potatoes as the anchor. Familiar first, new alongside.",
  },
  {
    id: "ciorba-legume", name: "Ciorbă de legume (vegetable sour soup)", time: 25, total: 45,
    serves: 6, tags: ["veg", "romanian", "batch", "kidsafe", "vegan", "nosugar"],
    macros: { kcal: 150, protein: 4, fat: 5, carbs: 21, sugars: 7, fibre: 5 },
    ingredients: [
      { n: "Carrots", q: "3", s: "produce" },
      { n: "Parsnip", q: "1", s: "produce" },
      { n: "Celery stalks", q: "2", s: "produce" },
      { n: "Potatoes", q: "3", s: "produce" },
      { n: "Red capsicum", q: "1", s: "produce" },
      { n: "Zucchini", q: "1", s: "produce" },
      { n: "Tinned tomatoes", q: "400 g", s: "pantry" },
      { n: "Borș or lemon juice", q: "to taste", s: "pantry" },
      { n: "Fresh parsley and lovage", q: "1 bunch", s: "produce" },
      { n: "Olive oil", q: "2 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Soften diced carrot, parsnip and celery in oil, about 8 minutes.",
      "Add potato, capsicum, tomatoes and 1.5 litres of water. Simmer 20 minutes.",
      "Add zucchini for the last 8 minutes. Sour with borș or lemon, finish with the herbs.",
    ],
    why: "A pot of mixed vegetables is variety made easy: different plants feed different gut bacteria, and variety across the week is what the fibre research keeps pointing to.",
    whySource: "World Cancer Research Fund; CSIRO gut health research",
    kidNote: "Blend a cup of the soup back in to thicken it. Same soup, friendlier texture.",
  },
  {
    id: "chicken-tray", name: "Paprika chicken with roast vegetables", time: 15, total: 50,
    serves: 4, tags: ["chicken", "oven", "kidsafe", "batch", "gf", "nosugar"],
    macros: { kcal: 570, protein: 38, fat: 30, carbs: 32, sugars: 13, fibre: 6 },
    ingredients: [
      { n: "Chicken thighs, bone in", q: "8", s: "fishmeat" },
      { n: "Sweet potato", q: "2", s: "produce" },
      { n: "Red onion", q: "2", s: "produce" },
      { n: "Capsicum", q: "2", s: "produce" },
      { n: "Smoked paprika", q: "2 tsp", s: "pantry", pantry: true },
      { n: "Olive oil", q: "3 tbsp", s: "pantry", pantry: true },
      { n: "Lemon", q: "1", s: "produce" },
    ],
    method: [
      "Heat the oven to 200°C. Toss chopped vegetables with oil, spread on a tray.",
      "Rub chicken with paprika, oil and salt. Place on top of the vegetables.",
      "Roast 35 to 40 minutes. Rest 5 minutes, squeeze over lemon.",
    ],
    why: "Skinless poultry with a tray of vegetables keeps the plate half plant, the pattern most national guidelines draw as the default dinner.",
    whySource: "Australian Dietary Guidelines (NHMRC)",
    kidNote: "Sweet potato usually wins the table. Let the vegetables roast until properly sweet.",
  },
  {
    id: "lentil-bolognese", name: "Lentil bolognese with wholemeal spaghetti", time: 25, total: 40,
    serves: 6, tags: ["legume", "veg", "batch", "kidsafe", "nosugar"],
    macros: { kcal: 510, protein: 22, fat: 11, carbs: 71, sugars: 11, fibre: 16 },
    ingredients: [
      { n: "Brown lentils, dry or tinned", q: "2 cups cooked", s: "pantry" },
      { n: "Wholemeal spaghetti", q: "500 g", s: "pantry" },
      { n: "Carrot", q: "2", s: "produce" },
      { n: "Celery stalks", q: "2", s: "produce" },
      { n: "Onion", q: "1", s: "produce" },
      { n: "Garlic", q: "3 cloves", s: "produce" },
      { n: "Tinned tomatoes", q: "2 x 400 g", s: "pantry" },
      { n: "Olive oil", q: "3 tbsp", s: "pantry", pantry: true },
      { n: "Parmesan", q: "to serve", s: "fridge" },
    ],
    method: [
      "Soften finely diced onion, carrot and celery in oil, 10 minutes. Add garlic.",
      "Add lentils and tomatoes, simmer 20 minutes until thick. Season well.",
      "Serve over spaghetti with parmesan. Freeze half the sauce for a rushed night.",
    ],
    why: "Legumes are the quiet star of the longevity literature: fibre, plant protein and minerals in one cheap ingredient. Twice a week is a good rhythm.",
    whySource: "World Cancer Research Fund; PREDIMED trial (Mediterranean pattern)",
    kidNote: "Looks like the bolognese they know. Start half lentil, half beef mince if the table is sceptical, then shift the ratio.",
  },
  {
    id: "fish-parcels", name: "White fish parcels with cherry tomatoes and olives", time: 15, total: 30,
    serves: 4, tags: ["fish", "quick", "oven", "nosugar"],
    macros: { kcal: 440, protein: 41, fat: 12, carbs: 37, sugars: 6, fibre: 7 },
    ingredients: [
      { n: "Firm white fish fillets", q: "4", s: "fishmeat" },
      { n: "Cherry tomatoes", q: "400 g", s: "produce" },
      { n: "Kalamata olives", q: "1/2 cup", s: "pantry" },
      { n: "Lemon", q: "1", s: "produce" },
      { n: "Olive oil", q: "2 tbsp", s: "pantry", pantry: true },
      { n: "Crusty wholegrain bread", q: "1 loaf", s: "bakery" },
    ],
    method: [
      "Heat the oven to 200°C. Place each fillet on baking paper with tomatoes, olives, oil and a lemon slice.",
      "Fold into sealed parcels, bake 15 minutes.",
      "Open at the table, serve with bread for the juices.",
    ],
    why: "Fish, olives, olive oil and tomatoes in one parcel is the Mediterranean pattern in miniature, the best-tested whole-diet pattern we have.",
    whySource: "PREDIMED trial; Heart Foundation",
    kidNote: "Parcels feel like presents. Let the kids open their own.",
  },
  {
    id: "mamaliga-greens", name: "Mămăligă with cheese, egg and garlicky greens", time: 25, total: 25,
    serves: 4, tags: ["veg", "romanian", "quick", "nosugar"],
    macros: { kcal: 470, protein: 19, fat: 21, carbs: 48, sugars: 2, fibre: 4 },
    ingredients: [
      { n: "Polenta", q: "1.5 cups", s: "pantry" },
      { n: "Telemea or feta", q: "150 g", s: "fridge" },
      { n: "Eggs", q: "4", s: "fridge" },
      { n: "Silverbeet or spinach", q: "1 large bunch", s: "produce" },
      { n: "Garlic", q: "4 cloves", s: "produce" },
      { n: "Olive oil", q: "2 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Whisk polenta into 6 cups of simmering salted water. Cook 20 minutes, stirring often.",
      "Wilt the greens with garlic and oil in a wide pan. Fry or poach the eggs.",
      "Serve mămăligă with crumbled cheese, greens and an egg on top.",
    ],
    why: "Comfort food and prevention are not opposites. Wholegrain corn, leafy greens and eggs make a complete plate that still tastes like home.",
    whySource: "Australian Dietary Guidelines (NHMRC)",
    kidNote: "Mămăligă with cheese rarely needs negotiation. The greens ride alongside, not hidden.",
  },
  {
    id: "chickpea-curry", name: "Coconut chickpea and pumpkin curry", time: 20, total: 35,
    serves: 5, tags: ["legume", "veg", "batch", "kidsafe", "gf", "nosugar", "vegan"],
    macros: { kcal: 530, protein: 16, fat: 11, carbs: 84, sugars: 10, fibre: 12 },
    ingredients: [
      { n: "Tinned chickpeas", q: "2 x 400 g", s: "pantry" },
      { n: "Pumpkin", q: "700 g", s: "produce" },
      { n: "Baby spinach", q: "120 g", s: "produce" },
      { n: "Light coconut milk", q: "400 ml", s: "pantry" },
      { n: "Mild curry paste", q: "3 tbsp", s: "pantry" },
      { n: "Brown rice", q: "2 cups", s: "pantry" },
      { n: "Onion", q: "1", s: "produce" },
    ],
    method: [
      "Cook the rice. Soften the onion, fry the curry paste 1 minute.",
      "Add pumpkin, chickpeas and coconut milk. Simmer 20 minutes until the pumpkin is soft.",
      "Stir through spinach at the end. Serve over rice.",
    ],
    why: "Chickpeas plus a golden vegetable plus brown rice covers fibre, plant protein and slow carbohydrate in one bowl.",
    whySource: "World Cancer Research Fund recommendations",
    kidNote: "Mild paste, and let the pumpkin melt into sweetness. Yoghurt on top for anyone who wants it milder still.",
  },
  {
    id: "minestrone", name: "Big-pot minestrone with white beans", time: 20, total: 45,
    serves: 6, tags: ["legume", "veg", "batch", "kidsafe", "nosugar"],
    macros: { kcal: 280, protein: 12, fat: 10, carbs: 30, sugars: 7, fibre: 10 },
    ingredients: [
      { n: "Cannellini beans, tinned", q: "2 x 400 g", s: "pantry" },
      { n: "Carrots", q: "2", s: "produce" },
      { n: "Zucchini", q: "2", s: "produce" },
      { n: "Green beans", q: "200 g", s: "produce" },
      { n: "Tinned tomatoes", q: "400 g", s: "pantry" },
      { n: "Small pasta shapes", q: "1 cup", s: "pantry" },
      { n: "Onion", q: "1", s: "produce" },
      { n: "Garlic", q: "3 cloves", s: "produce" },
      { n: "Parmesan", q: "to serve", s: "fridge" },
      { n: "Olive oil", q: "3 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Soften onion, carrot and garlic in oil. Add tomatoes and 1.5 litres of water or stock.",
      "Simmer 15 minutes, add beans, pasta and green vegetables, cook 12 minutes more.",
      "Serve with parmesan. It is better tomorrow: make the full pot.",
    ],
    why: "Soup is the easiest way to eat five different plants in one sitting, and the leftovers solve a second night.",
    whySource: "Australian Dietary Guidelines; CSIRO gut health research",
    kidNote: "The little pasta shapes carry the soup. Keep the vegetable dice small.",
  },
  {
    id: "beef-stirfry", name: "Beef and broccoli stir-fry with brown rice", time: 20, total: 20,
    serves: 4, tags: ["quick", "nosugar"],
    macros: { kcal: 530, protein: 32, fat: 8, carbs: 75, sugars: 4, fibre: 7 },
    ingredients: [
      { n: "Lean beef strips", q: "400 g", s: "fishmeat" },
      { n: "Broccoli", q: "1 large head", s: "produce" },
      { n: "Capsicum", q: "1", s: "produce" },
      { n: "Spring onions", q: "4", s: "produce" },
      { n: "Ginger", q: "3 cm piece", s: "produce" },
      { n: "Reduced-salt soy sauce", q: "3 tbsp", s: "pantry", pantry: true },
      { n: "Brown rice", q: "2 cups", s: "pantry" },
    ],
    method: [
      "Cook the rice. Sear the beef hard in two batches, set aside.",
      "Stir-fry broccoli, capsicum and ginger 3 minutes with a splash of water.",
      "Return the beef with soy and the spring onions. Toss and serve.",
    ],
    why: "Red meat fits a healthy pattern in modest amounts: the research draws the line at roughly three serves a week, with vegetables doing the volume.",
    whySource: "World Cancer Research Fund; Australian Dietary Guidelines",
    kidNote: "Separate the components on the plate for anyone anti-sauce.",
  },
  {
    id: "salmon-pasta", name: "15-minute salmon and pea pasta", time: 15, total: 15,
    serves: 4, tags: ["fish", "quick", "kidsafe", "nosugar"],
    macros: { kcal: 600, protein: 40, fat: 13, carbs: 72, sugars: 7, fibre: 13 },
    ingredients: [
      { n: "Tinned salmon", q: "2 x 210 g", s: "pantry" },
      { n: "Wholemeal pasta", q: "400 g", s: "pantry" },
      { n: "Frozen peas", q: "2 cups", s: "frozen" },
      { n: "Lemon", q: "1", s: "produce" },
      { n: "Greek yoghurt", q: "3/4 cup", s: "fridge" },
      { n: "Dill or parsley", q: "1/2 bunch", s: "produce" },
    ],
    method: [
      "Cook the pasta, adding peas for the last 3 minutes. Keep a cup of pasta water.",
      "Stir yoghurt, lemon zest and juice, and flaked salmon through the drained pasta.",
      "Loosen with pasta water, finish with herbs.",
    ],
    why: "Tinned salmon keeps the fish habit alive on the weeks when fresh fish does not happen. The tin is not a compromise; it is a strategy.",
    whySource: "Heart Foundation (Australia)",
    kidNote: "Peas and pasta do the reassuring. This one is a reliable rushed-Tuesday dinner.",
  },
  {
    id: "sarmale-light", name: "Weeknight cabbage roll bowls (sarmale flavours)", time: 25, total: 40,
    serves: 5, tags: ["romanian", "batch", "nosugar"],
    macros: { kcal: 470, protein: 24, fat: 15, carbs: 53, sugars: 10, fibre: 6 },
    ingredients: [
      { n: "Lean pork and beef mince", q: "400 g", s: "fishmeat" },
      { n: "Savoy cabbage", q: "1/2 head", s: "produce" },
      { n: "Brown rice", q: "1.5 cups", s: "pantry" },
      { n: "Tinned tomatoes", q: "400 g", s: "pantry" },
      { n: "Onion", q: "2", s: "produce" },
      { n: "Smoked paprika", q: "2 tsp", s: "pantry", pantry: true },
      { n: "Dill", q: "1/2 bunch", s: "produce" },
      { n: "Greek yoghurt", q: "to serve", s: "fridge" },
    ],
    method: [
      "Cook the rice. Brown the mince with onion and paprika.",
      "Add shredded cabbage and tomatoes, cover and simmer 15 minutes.",
      "Serve over rice with dill and a spoon of yoghurt. All the sarmale flavour, quarter of the work.",
    ],
    why: "Traditional food adapted, not abandoned: more cabbage and rice, less meat, same taste memory. Sustainable change keeps the culture in the kitchen.",
    whySource: "Australian Dietary Guidelines",
    kidNote: "Deconstructed means everyone assembles their own ratio.",
  },
  {
    id: "shakshuka", name: "Shakshuka with white beans", time: 25, total: 25,
    serves: 4, tags: ["veg", "quick", "legume", "nosugar"],
    macros: { kcal: 500, protein: 27, fat: 15, carbs: 56, sugars: 16, fibre: 13 },
    ingredients: [
      { n: "Eggs", q: "6", s: "fridge" },
      { n: "Tinned tomatoes", q: "2 x 400 g", s: "pantry" },
      { n: "Cannellini beans, tinned", q: "400 g", s: "pantry" },
      { n: "Capsicum", q: "2", s: "produce" },
      { n: "Onion", q: "1", s: "produce" },
      { n: "Cumin and paprika", q: "1 tsp each", s: "pantry", pantry: true },
      { n: "Feta", q: "80 g", s: "fridge" },
      { n: "Wholegrain bread", q: "1 loaf", s: "bakery" },
    ],
    method: [
      "Soften onion and capsicum, add spices, then tomatoes and beans. Simmer 10 minutes.",
      "Make wells, crack in the eggs, cover until just set.",
      "Crumble over feta, serve with bread for dipping.",
    ],
    why: "Eggs are back in the good books for most people, and a tomato-bean base turns them into a full plant-forward dinner.",
    whySource: "Heart Foundation position on eggs; Australian Dietary Guidelines",
    kidNote: "Rename it eggs-in-sauce and serve with plenty of bread.",
  },
  {
    id: "roast-veg-couscous", name: "Roast vegetable and chickpea couscous", time: 15, total: 40,
    serves: 4, tags: ["veg", "legume", "oven", "batch", "vegan", "nosugar"],
    macros: { kcal: 550, protein: 18, fat: 18, carbs: 70, sugars: 11, fibre: 14 },
    ingredients: [
      { n: "Pumpkin", q: "500 g", s: "produce" },
      { n: "Zucchini", q: "2", s: "produce" },
      { n: "Red onion", q: "2", s: "produce" },
      { n: "Tinned chickpeas", q: "400 g", s: "pantry" },
      { n: "Wholemeal couscous", q: "1.5 cups", s: "pantry" },
      { n: "Lemon", q: "1", s: "produce" },
      { n: "Olive oil", q: "3 tbsp", s: "pantry", pantry: true },
      { n: "Almonds", q: "1/2 cup", s: "pantry" },
      { n: "Mint or parsley", q: "1/2 bunch", s: "produce" },
    ],
    method: [
      "Roast chopped vegetables and drained chickpeas with oil at 210°C for 30 minutes.",
      "Soak couscous in boiling water, fluff with lemon juice and oil.",
      "Top with the tray, scatter almonds and herbs. Leftovers are tomorrow's lunch.",
    ],
    why: "A handful of nuts most days tracks with better heart outcomes in trial after trial. Toasted on dinner is an easy place for them.",
    whySource: "PREDIMED trial; Heart Foundation",
    kidNote: "Couscous is famously spoon-friendly. Keep a plain-roasted corner of the tray.",
  },
  {
    id: "chicken-soup", name: "Chicken, vegetable and barley soup", time: 20, total: 55,
    serves: 6, tags: ["chicken", "batch", "kidsafe", "nosugar"],
    macros: { kcal: 300, protein: 19, fat: 14, carbs: 21, sugars: 2, fibre: 6 },
    ingredients: [
      { n: "Chicken thighs", q: "500 g", s: "fishmeat" },
      { n: "Pearl barley", q: "3/4 cup", s: "pantry" },
      { n: "Carrots", q: "3", s: "produce" },
      { n: "Celery stalks", q: "3", s: "produce" },
      { n: "Leek", q: "1", s: "produce" },
      { n: "Parsley", q: "1/2 bunch", s: "produce" },
      { n: "Olive oil", q: "2 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Soften leek, carrot and celery in oil. Add chicken, barley and 2 litres of water.",
      "Simmer 40 minutes. Shred the chicken back into the pot.",
      "Season well, finish with parsley. Freezes beautifully.",
    ],
    why: "Barley is one of the highest soluble-fibre grains on the shelf. Swapping it into familiar soup is change nobody at the table notices.",
    whySource: "CSIRO; Grains and Legumes Nutrition Council",
    kidNote: "It is chicken soup. This one sells itself.",
  },
  {
    id: "fish-tacos", name: "Grilled fish tacos with cabbage slaw", time: 25, total: 25,
    serves: 4, tags: ["fish", "quick", "kidsafe", "nosugar"],
    macros: { kcal: 460, protein: 38, fat: 12, carbs: 49, sugars: 8, fibre: 10 },
    ingredients: [
      { n: "Firm white fish fillets", q: "500 g", s: "fishmeat" },
      { n: "Corn or wholemeal tortillas", q: "8", s: "bakery" },
      { n: "Red cabbage", q: "1/4 head", s: "produce" },
      { n: "Corn cobs", q: "2", s: "produce" },
      { n: "Lime", q: "2", s: "produce" },
      { n: "Greek yoghurt", q: "3/4 cup", s: "fridge" },
      { n: "Avocado", q: "1", s: "produce" },
      { n: "Ground cumin", q: "1 tsp", s: "pantry", pantry: true },
    ],
    method: [
      "Rub fish with cumin and oil, grill or pan-fry, then flake.",
      "Toss shredded cabbage with lime and a pinch of salt. Char the corn, slice off the cob.",
      "Warm tortillas, build at the table with yoghurt and avocado.",
    ],
    why: "Build-your-own dinners quietly raise vegetable intake: people take more of what they assemble themselves. That is behavioural science doing the parenting.",
    whySource: "Appetite research on child food acceptance; Australian Dietary Guidelines",
    kidNote: "Assembly is the fun. Nobody has to take the slaw, and most eventually do.",
  },
  {
    id: "tofu-noodles", name: "Crispy tofu and vegetable noodles", time: 25, total: 25,
    serves: 4, tags: ["veg", "quick", "vegan", "nosugar"],
    macros: { kcal: 550, protein: 27, fat: 12, carbs: 76, sugars: 8, fibre: 12 },
    ingredients: [
      { n: "Firm tofu", q: "450 g", s: "fridge" },
      { n: "Wholemeal noodles", q: "375 g", s: "pantry" },
      { n: "Broccoli", q: "1 head", s: "produce" },
      { n: "Carrots", q: "2", s: "produce" },
      { n: "Snow peas", q: "150 g", s: "produce" },
      { n: "Reduced-salt soy sauce", q: "3 tbsp", s: "pantry", pantry: true },
      { n: "Sesame oil", q: "1 tbsp", s: "pantry", pantry: true },
      { n: "Cornflour", q: "2 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Press tofu, cube, toss in cornflour, pan-fry until golden on all sides.",
      "Cook noodles. Stir-fry vegetables 3 minutes.",
      "Combine everything with soy and sesame oil.",
    ],
    why: "Soy foods are a well-studied plant protein, and the evidence on them is reassuring, including for people after a cancer diagnosis. Crispy is the gateway texture.",
    whySource: "Cancer Council Australia position on soy",
    kidNote: "Golden cubes plus noodles is a fair trade for trying one green thing.",
  },
  {
    id: "baked-risotto", name: "Oven-baked pumpkin and spinach risotto", time: 15, total: 45,
    serves: 4, tags: ["veg", "oven", "kidsafe", "batch", "gf", "nosugar"],
    macros: { kcal: 490, protein: 17, fat: 13, carbs: 72, sugars: 8, fibre: 4 },
    ingredients: [
      { n: "Arborio rice", q: "1.5 cups", s: "pantry" },
      { n: "Pumpkin", q: "600 g", s: "produce" },
      { n: "Baby spinach", q: "120 g", s: "produce" },
      { n: "Onion", q: "1", s: "produce" },
      { n: "Parmesan", q: "80 g", s: "fridge" },
      { n: "Olive oil", q: "2 tbsp", s: "pantry", pantry: true },
      { n: "Stock, reduced salt", q: "1 litre", s: "pantry" },
    ],
    method: [
      "Heat the oven to 200°C. Soften the onion in an ovenproof pot, stir in rice.",
      "Add stock and pumpkin, cover, bake 30 minutes. No stirring.",
      "Fold through spinach and parmesan. Rest 5 minutes.",
    ],
    why: "The oven does the famous stirring. Removing effort is the most reliable way to make a good habit survive a school term.",
    whySource: "Behavioural habit research (habit formation via friction reduction)",
    kidNote: "Orange and creamy. One of the easiest full-vegetable dinners there is.",
  },
  {
    id: "burgers-home", name: "Homemade beef and lentil burgers", time: 30, total: 30,
    serves: 4, tags: ["kidsafe", "legume", "nosugar"],
    macros: { kcal: 540, protein: 33, fat: 12, carbs: 66, sugars: 15, fibre: 15 },
    ingredients: [
      { n: "Lean beef mince", q: "300 g", s: "fishmeat" },
      { n: "Brown lentils, tinned", q: "400 g", s: "pantry" },
      { n: "Wholemeal burger buns", q: "4", s: "bakery" },
      { n: "Egg", q: "1", s: "fridge" },
      { n: "Tomatoes", q: "2", s: "produce" },
      { n: "Lettuce", q: "1 head", s: "produce" },
      { n: "Red onion", q: "1", s: "produce" },
      { n: "Sweet potato", q: "2", s: "produce" },
    ],
    method: [
      "Roast sweet potato wedges at 210°C, about 25 minutes.",
      "Mash drained lentils, mix with mince, egg and seasoning. Shape 4 patties, pan-fry 4 minutes a side.",
      "Build burgers with salad. Friday night, solved at home.",
    ],
    why: "The takeaway burger is not the enemy; the default is. A home version with half lentils keeps the ritual and changes the pattern.",
    whySource: "Australian Dietary Guidelines; WCRF on limiting fast food patterns",
    kidNote: "Nobody has ever detected the lentils. This stays between us.",
  },
  {
    id: "nicoise", name: "Warm tuna niçoise-style salad", time: 20, total: 20,
    serves: 4, tags: ["fish", "quick", "gf", "nosugar"],
    macros: { kcal: 360, protein: 30, fat: 13, carbs: 28, sugars: 5, fibre: 6 },
    ingredients: [
      { n: "Tinned tuna in oil", q: "2 x 185 g", s: "pantry" },
      { n: "Baby potatoes", q: "600 g", s: "produce" },
      { n: "Green beans", q: "300 g", s: "produce" },
      { n: "Eggs", q: "4", s: "fridge" },
      { n: "Cherry tomatoes", q: "250 g", s: "produce" },
      { n: "Olives", q: "1/2 cup", s: "pantry" },
      { n: "Olive oil and red wine vinegar", q: "for dressing", s: "pantry", pantry: true },
    ],
    method: [
      "Boil potatoes; add beans for the last 3 minutes. Soft-boil the eggs, 7 minutes.",
      "Toss everything with olive oil, vinegar, salt and pepper while warm.",
      "Top with tuna and halved eggs.",
    ],
    why: "A salad that counts as dinner because it is built on potatoes, eggs and fish. Warm vegetables take dressing better, so more salad gets eaten.",
    whySource: "Mediterranean dietary pattern evidence (PREDIMED)",
    kidNote: "Serve it deconstructed: potato, egg, beans, tomato in their own zones.",
  },
  {
    id: "veg-frittata", name: "Fridge-clearing vegetable frittata", time: 15, total: 35,
    serves: 4, tags: ["veg", "quick", "kidsafe", "keto", "gf", "nosugar"], netCarbs: 11,
    macros: { kcal: 340, protein: 20, fat: 22, carbs: 11, sugars: 7, fibre: 5 },
    ingredients: [
      { n: "Eggs", q: "8", s: "fridge" },
      { n: "Zucchini", q: "1", s: "produce" },
      { n: "Cherry tomatoes", q: "200 g", s: "produce" },
      { n: "Frozen peas", q: "1 cup", s: "frozen" },
      { n: "Feta or cheddar", q: "100 g", s: "fridge" },
      { n: "Whatever vegetables are left", q: "2 cups", s: "produce" },
      { n: "Olive oil", q: "2 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Heat the oven to 180°C. Soften the vegetables in an ovenproof pan.",
      "Pour over whisked eggs, scatter cheese, bake 20 minutes until set.",
      "Serve with bread and whatever salad survived the week.",
    ],
    why: "The end-of-week frittata rescues vegetables before they become waste. Less waste, one more vegetable dinner: the same move wins twice.",
    whySource: "Australian Dietary Guidelines",
    kidNote: "Call it egg pie. Squares are more convincing than wedges.",
  },
  {
    id: "pork-apple-tray", name: "Pork, apple and cabbage tray bake", time: 15, total: 40,
    serves: 4, tags: ["oven", "gf", "nosugar"],
    macros: { kcal: 530, protein: 38, fat: 21, carbs: 48, sugars: 18, fibre: 10 },
    ingredients: [
      { n: "Pork loin steaks", q: "4", s: "fishmeat" },
      { n: "Apples", q: "2", s: "produce" },
      { n: "Savoy cabbage", q: "1/2 head", s: "produce" },
      { n: "Red onion", q: "2", s: "produce" },
      { n: "Baby potatoes", q: "700 g", s: "produce" },
      { n: "Fennel seeds", q: "1 tsp", s: "pantry", pantry: true },
      { n: "Olive oil", q: "3 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Roast potatoes, cabbage wedges and onion with oil at 200°C for 20 minutes.",
      "Add pork and apple wedges with fennel seeds, roast 15 minutes more.",
      "Rest the pork 5 minutes before serving.",
    ],
    why: "Fresh pork is not processed meat: it is the salami-bacon-ham category the cancer research flags to keep low, not the Sunday roast.",
    whySource: "World Cancer Research Fund on processed meat",
    kidNote: "Roast apple makes the whole tray taste friendlier.",
  },
  {
    id: "dahl", name: "Red lentil dahl with cucumber yoghurt", time: 20, total: 35,
    serves: 5, tags: ["legume", "veg", "batch", "kidsafe", "gf", "nosugar"],
    macros: { kcal: 640, protein: 30, fat: 5, carbs: 110, sugars: 9, fibre: 11 },
    ingredients: [
      { n: "Red lentils", q: "2 cups", s: "pantry" },
      { n: "Tinned tomatoes", q: "400 g", s: "pantry" },
      { n: "Onion", q: "1", s: "produce" },
      { n: "Garlic", q: "3 cloves", s: "produce" },
      { n: "Ginger", q: "3 cm piece", s: "produce" },
      { n: "Turmeric and cumin", q: "1 tsp each", s: "pantry", pantry: true },
      { n: "Cucumber", q: "1", s: "produce" },
      { n: "Greek yoghurt", q: "1 cup", s: "fridge" },
      { n: "Basmati rice", q: "2 cups", s: "pantry" },
    ],
    method: [
      "Soften onion, garlic and ginger; bloom the spices 1 minute.",
      "Add lentils, tomatoes and 4 cups of water. Simmer 25 minutes, stirring near the end.",
      "Serve with rice and grated-cucumber yoghurt. Freeze the extra.",
    ],
    why: "Red lentils cook from dry in under half an hour, the cheapest fibre in the supermarket. Cheap matters: patterns only hold if the budget does.",
    whySource: "Grains and Legumes Nutrition Council; WCRF",
    kidNote: "Mild, golden and scoopable. The yoghurt bowl is the child magnet.",
  },
  {
    id: "greek-chicken-bowls", name: "Greek chicken and grain bowls", time: 25, total: 25,
    serves: 4, tags: ["chicken", "quick", "gf", "nosugar"],
    macros: { kcal: 520, protein: 46, fat: 12, carbs: 48, sugars: 8, fibre: 10 },
    ingredients: [
      { n: "Chicken breast", q: "500 g", s: "fishmeat" },
      { n: "Freekeh or brown rice", q: "1.5 cups", s: "pantry" },
      { n: "Cucumber", q: "2", s: "produce" },
      { n: "Cherry tomatoes", q: "250 g", s: "produce" },
      { n: "Greek yoghurt", q: "1 cup", s: "fridge" },
      { n: "Lemon", q: "1", s: "produce" },
      { n: "Dried oregano", q: "2 tsp", s: "pantry", pantry: true },
      { n: "Feta", q: "80 g", s: "fridge" },
    ],
    method: [
      "Cook the grain. Slice chicken, toss with oregano, lemon and oil, pan-fry.",
      "Chop the salad vegetables. Make a quick lemon-yoghurt sauce.",
      "Build bowls: grain, chicken, salad, feta, sauce.",
    ],
    why: "The bowl formula (grain + protein + two vegetables + yoghurt) is infinitely reusable. Learn the formula once and a dozen dinners fall out of it.",
    whySource: "Mediterranean dietary pattern evidence",
    kidNote: "Bowls mean control. Sauce on the side settles most disputes.",
  },
  {
    id: "zacusca-pasta", name: "Zacuscă-style capsicum and eggplant pasta", time: 20, total: 40,
    serves: 4, tags: ["veg", "romanian", "batch", "nosugar"],
    macros: { kcal: 580, protein: 17, fat: 17, carbs: 81, sugars: 18, fibre: 16 },
    ingredients: [
      { n: "Eggplant", q: "1 large", s: "produce" },
      { n: "Red capsicum", q: "3", s: "produce" },
      { n: "Onion", q: "2", s: "produce" },
      { n: "Tinned tomatoes", q: "400 g", s: "pantry" },
      { n: "Wholemeal penne", q: "400 g", s: "pantry" },
      { n: "Olive oil", q: "4 tbsp", s: "pantry", pantry: true },
      { n: "Parsley", q: "1/2 bunch", s: "produce" },
    ],
    method: [
      "Roast eggplant and capsicum at 220°C until soft and charred at the edges, 25 minutes.",
      "Soften onion, add tomatoes and the chopped roasted vegetables, simmer 10 minutes.",
      "Toss through pasta. The sauce is zacuscă's weeknight cousin; it freezes well.",
    ],
    why: "Roasted capsicum and eggplant carry the flavours of home preserving without the all-day project. Taste memory is a lever, not an obstacle.",
    whySource: "Mediterranean dietary pattern evidence",
    kidNote: "Blend the sauce smooth if texture is the objection.",
  },
  {
    id: "banh-mi-bowls", name: "Chicken bánh mì-style rice bowls", time: 25, total: 25,
    serves: 4, tags: ["chicken", "quick", "nosugar"],
    macros: { kcal: 560, protein: 30, fat: 11, carbs: 82, sugars: 3, fibre: 3 },
    ingredients: [
      { n: "Chicken mince", q: "500 g", s: "fishmeat" },
      { n: "Jasmine or brown rice", q: "2 cups", s: "pantry" },
      { n: "Carrots", q: "2", s: "produce" },
      { n: "Cucumber", q: "1", s: "produce" },
      { n: "Coriander", q: "1/2 bunch", s: "produce" },
      { n: "Rice wine vinegar", q: "3 tbsp", s: "pantry", pantry: true },
      { n: "Reduced-salt soy sauce", q: "2 tbsp", s: "pantry", pantry: true },
      { n: "Lime", q: "1", s: "produce" },
    ],
    method: [
      "Cook the rice. Quick-pickle ribboned carrot and cucumber in vinegar with a pinch of sugar and salt.",
      "Brown the chicken mince hard, season with soy and lime.",
      "Bowls: rice, chicken, pickles, coriander.",
    ],
    why: "Quick pickles make raw vegetables interesting, and vinegar costs nothing nutritionally. Interesting vegetables get eaten; worthy ones get left.",
    whySource: "Australian Dietary Guidelines",
    kidNote: "Pickles optional, lime in everything. The mince is the safe harbour.",
  },
  {
    id: "mushroom-barley", name: "Mushroom and barley one-pot", time: 15, total: 45,
    serves: 4, tags: ["veg", "batch", "oven", "nosugar"],
    macros: { kcal: 480, protein: 20, fat: 16, carbs: 60, sugars: 4, fibre: 15 },
    ingredients: [
      { n: "Mushrooms", q: "600 g", s: "produce" },
      { n: "Pearl barley", q: "1.5 cups", s: "pantry" },
      { n: "Onion", q: "1", s: "produce" },
      { n: "Garlic", q: "4 cloves", s: "produce" },
      { n: "Thyme", q: "4 sprigs", s: "produce" },
      { n: "Stock, reduced salt", q: "1 litre", s: "pantry" },
      { n: "Parmesan", q: "60 g", s: "fridge" },
      { n: "Olive oil", q: "3 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Brown the mushrooms properly in batches. Soften onion and garlic.",
      "Add barley, thyme and stock. Cover, simmer 35 minutes.",
      "Finish with parmesan. Deep flavour, one pot.",
    ],
    why: "Mushrooms plus barley is umami plus soluble fibre: satisfying enough that nobody asks where the meat went.",
    whySource: "CSIRO; Grains and Legumes Nutrition Council",
    kidNote: "For mushroom sceptics, chop them fine so they season rather than star.",
  },

  // ---------- ketogenic set (netCarbs = approximate grams per serve) ----------
  {
    id: "keto-salmon-greens", name: "Lemon-butter salmon with garlicky greens", time: 15, total: 20,
    serves: 4, tags: ["fish", "keto", "quick", "kidsafe", "nosugar"], netCarbs: 6,
    macros: { kcal: 490, protein: 34, fat: 36, carbs: 5, sugars: 2, fibre: 4 },
    ingredients: [
      { n: "Salmon fillets", q: "4", s: "fishmeat" },
      { n: "Broccolini", q: "2 bunches", s: "produce" },
      { n: "Baby spinach", q: "150 g", s: "produce" },
      { n: "Butter", q: "60 g", s: "fridge" },
      { n: "Lemon", q: "1", s: "produce" },
      { n: "Garlic", q: "3 cloves", s: "produce" },
      { n: "Olive oil", q: "1 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Pan-sear the salmon in oil, skin down, 4 minutes; turn for 2 more. Rest on a plate.",
      "In the same pan, melt butter with garlic. Toss broccolini 3 minutes, wilt in the spinach.",
      "Return salmon, squeeze the lemon over everything, spoon the pan butter on top.",
    ],
    why: "The keto version of the fish rule: the omega-3 evidence stays, the potatoes wait for another night.",
    whySource: "Heart Foundation (Australia)",
    kidNote: "Kids' plates can add rice or bread; ketosis is an adult's tool, never a child's diet.",
  },
  {
    id: "keto-butter-chicken", name: "Butter chicken with cauliflower rice", time: 25, total: 35,
    serves: 5, tags: ["chicken", "keto", "batch", "kidsafe", "gf", "nosugar"], netCarbs: 10,
    macros: { kcal: 610, protein: 35, fat: 48, carbs: 9, sugars: 7, fibre: 4 },
    ingredients: [
      { n: "Chicken thigh fillets", q: "800 g", s: "fishmeat" },
      { n: "Cauliflower", q: "1 large head", s: "produce" },
      { n: "Tinned tomatoes", q: "400 g", s: "pantry" },
      { n: "Thickened cream", q: "300 ml", s: "fridge" },
      { n: "Butter", q: "50 g", s: "fridge" },
      { n: "Garam masala, cumin, paprika", q: "1 tbsp each", s: "pantry", pantry: true },
      { n: "Ginger", q: "3 cm", s: "produce" },
      { n: "Garlic", q: "4 cloves", s: "produce" },
    ],
    method: [
      "Brown chicken pieces in half the butter. Set aside.",
      "Soften garlic, ginger and spices in the rest. Add tomatoes, simmer 5 minutes, then cream and chicken; simmer 15.",
      "Blitz cauliflower into rice, sauté 4 minutes, serve under the curry.",
    ],
    why: "Comfort food that keeps carbs near ten grams: the trick to a sustainable keto is that dinner still feels like dinner.",
    whySource: "Virta Health trial protocol (real-food ketogenic practice)",
    kidNote: "Mild by default; the same sauce works over basmati for the kids.",
  },
  {
    id: "keto-mititei", name: "Mititei-style patties with cabbage salad", time: 25, total: 25,
    serves: 4, tags: ["keto", "romanian", "quick", "nosugar"], netCarbs: 5,
    macros: { kcal: 600, protein: 34, fat: 49, carbs: 5, sugars: 4, fibre: 3 },
    ingredients: [
      { n: "Beef mince", q: "500 g", s: "fishmeat" },
      { n: "Pork mince", q: "250 g", s: "fishmeat" },
      { n: "White cabbage", q: "1/2 head", s: "produce" },
      { n: "Dill", q: "1/2 bunch", s: "produce" },
      { n: "Lemon", q: "1", s: "produce" },
      { n: "Garlic", q: "4 cloves", s: "produce" },
      { n: "Bicarb soda, thyme, paprika", q: "1 tsp each", s: "pantry", pantry: true },
      { n: "Olive oil", q: "3 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Knead minces with garlic, spices, bicarb and a splash of water until sticky. Shape into little rolls.",
      "Grill or pan-fry 4 to 5 minutes a side.",
      "Shred cabbage fine, salt it, squeeze it, dress with lemon, oil and dill.",
    ],
    why: "The grill-house classic, kept honest: protein and cabbage, no chips needed. Familiar food is what makes any way of eating last.",
    whySource: "Adherence literature: the diet you keep is the one that works (Annual Review of Nutrition, 2021)",
  },
  {
    id: "keto-zoodle-carbonara", name: "Zucchini carbonara", time: 20, total: 20,
    serves: 4, tags: ["keto", "quick", "veg", "gf", "nosugar"], netCarbs: 6,
    macros: { kcal: 360, protein: 21, fat: 28, carbs: 6, sugars: 4, fibre: 3 },
    ingredients: [
      { n: "Zucchini", q: "5 large", s: "produce" },
      { n: "Eggs", q: "3", s: "fridge" },
      { n: "Parmesan", q: "80 g", s: "fridge" },
      { n: "Bacon or pancetta", q: "150 g", s: "fishmeat" },
      { n: "Garlic", q: "2 cloves", s: "produce" },
      { n: "Olive oil", q: "1 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Ribbon or spiralise the zucchini. Salt lightly, rest 10 minutes, pat dry.",
      "Crisp the bacon with garlic. Whisk eggs with parmesan.",
      "Toss zucchini in the hot pan 2 minutes, kill the heat, fold through the egg mix until silky.",
    ],
    why: "Processed meat stays occasional in Harta's world even in keto mode: the WCRF signal on bacon does not disappear because carbs did.",
    whySource: "World Cancer Research Fund (processed meat guidance)",
  },
  {
    id: "keto-pork-cabbage", name: "Pork and caraway cabbage skillet", time: 20, total: 35,
    serves: 4, tags: ["keto", "romanian", "batch", "gf", "nosugar"], netCarbs: 13,
    macros: { kcal: 580, protein: 34, fat: 42, carbs: 13, sugars: 10, fibre: 6 },
    ingredients: [
      { n: "Pork shoulder or scotch, diced", q: "700 g", s: "fishmeat" },
      { n: "White cabbage", q: "1 head", s: "produce" },
      { n: "Onion", q: "1", s: "produce" },
      { n: "Caraway seeds", q: "2 tsp", s: "pantry", pantry: true },
      { n: "Smoked paprika", q: "2 tsp", s: "pantry", pantry: true },
      { n: "Sour cream", q: "150 g", s: "fridge" },
      { n: "Olive oil", q: "2 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Brown the pork hard in oil. Set aside.",
      "Soften onion, then a mountain of shredded cabbage with caraway and paprika until sweet and collapsed, 12 minutes.",
      "Return the pork, splash of water, lid on 10 minutes. Serve with sour cream.",
    ],
    why: "Varză călită flavours, weeknight speed. Cabbage is the quiet hero of low-carb cooking: volume, crunch and brassica compounds for almost no carbs.",
    whySource: "World Cancer Research Fund (cruciferous vegetables)",
  },
  {
    id: "keto-lettuce-tacos", name: "Beef lettuce-cup tacos", time: 20, total: 20,
    serves: 4, tags: ["keto", "quick", "kidsafe", "gf", "nosugar"], netCarbs: 8,
    macros: { kcal: 690, protein: 37, fat: 56, carbs: 8, sugars: 5, fibre: 7 },
    ingredients: [
      { n: "Beef mince", q: "600 g", s: "fishmeat" },
      { n: "Baby cos lettuce", q: "3 heads", s: "produce" },
      { n: "Avocado", q: "2", s: "produce" },
      { n: "Cherry tomatoes", q: "200 g", s: "produce" },
      { n: "Tasty cheese, grated", q: "100 g", s: "fridge" },
      { n: "Sour cream", q: "150 g", s: "fridge" },
      { n: "Cumin, smoked paprika, oregano", q: "1 tsp each", s: "pantry", pantry: true },
      { n: "Lime", q: "2", s: "produce" },
    ],
    method: [
      "Brown the mince with the spices; splash of water to make it saucy.",
      "Separate lettuce leaves into cups. Dice avocado and tomatoes with lime and salt.",
      "Build at the table: everyone loads their own.",
    ],
    why: "Build-your-own dinners survive family life: same ingredients, each plate its own way, and the keto plate just skips the shells.",
    whySource: "Family-meals research: shared assembly increases vegetable acceptance (Appetite journal)",
    kidNote: "Kids get taco shells or wraps alongside; the filling is identical.",
  },
  {
    id: "keto-mushroom-soup", name: "Creamy mushroom and thyme soup", time: 20, total: 35,
    serves: 5, tags: ["keto", "veg", "batch", "gf", "nosugar"], netCarbs: 6,
    macros: { kcal: 310, protein: 7, fat: 29, carbs: 6, sugars: 4, fibre: 3 },
    ingredients: [
      { n: "Mushrooms", q: "700 g", s: "produce" },
      { n: "Leek", q: "1", s: "produce" },
      { n: "Garlic", q: "4 cloves", s: "produce" },
      { n: "Thyme", q: "5 sprigs", s: "produce" },
      { n: "Thickened cream", q: "300 ml", s: "fridge" },
      { n: "Stock, reduced salt", q: "750 ml", s: "pantry" },
      { n: "Butter", q: "40 g", s: "fridge" },
    ],
    method: [
      "Brown mushrooms in butter in two batches; do not crowd the pan.",
      "Soften leek and garlic, return mushrooms, add stock and thyme, simmer 15 minutes.",
      "Blend most of it, keep some chunks, finish with cream.",
    ],
    why: "A batch soup that freezes well keeps the rushed nights honest in keto mode too.",
    whySource: "Meal-planning adherence literature",
  },
  {
    id: "keto-eggplant-bake", name: "Eggplant, ricotta and basil bake", time: 25, total: 55,
    serves: 5, tags: ["keto", "veg", "oven", "batch", "nosugar"], netCarbs: 18,
    macros: { kcal: 470, protein: 25, fat: 31, carbs: 18, sugars: 12, fibre: 7 },
    ingredients: [
      { n: "Eggplants", q: "3", s: "produce" },
      { n: "Ricotta", q: "400 g", s: "fridge" },
      { n: "Tinned tomatoes", q: "800 g", s: "pantry" },
      { n: "Mozzarella", q: "200 g", s: "fridge" },
      { n: "Parmesan", q: "60 g", s: "fridge" },
      { n: "Basil", q: "1 bunch", s: "produce" },
      { n: "Garlic", q: "4 cloves", s: "produce" },
      { n: "Olive oil", q: "4 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Slice eggplant 1 cm, brush with oil, roast 20 minutes at 210°C.",
      "Simmer tomatoes with garlic into a quick sauce.",
      "Layer eggplant, sauce, ricotta and basil; top with mozzarella and parmesan. Bake 25 minutes.",
    ],
    why: "Lasagne comfort with vegetables as the pasta. The Mediterranean and ketogenic patterns overlap right here: olive oil, vegetables, cheese, herbs.",
    whySource: "PREDIMED (olive-oil pattern); ketogenic practice",
    kidNote: "Serve with garlic bread for the non-keto table.",
  },
  {
    id: "keto-cobb", name: "Chicken cobb salad with soft eggs", time: 20, total: 20,
    serves: 4, tags: ["keto", "quick", "chicken", "gf", "nosugar"], netCarbs: 7,
    macros: { kcal: 540, protein: 41, fat: 37, carbs: 6, sugars: 4, fibre: 6 },
    ingredients: [
      { n: "Chicken breast", q: "500 g", s: "fishmeat" },
      { n: "Eggs", q: "4", s: "fridge" },
      { n: "Baby cos lettuce", q: "2 heads", s: "produce" },
      { n: "Avocado", q: "2", s: "produce" },
      { n: "Cherry tomatoes", q: "250 g", s: "produce" },
      { n: "Danish feta", q: "100 g", s: "fridge" },
      { n: "Olive oil and red wine vinegar", q: "3 tbsp + 1 tbsp", s: "pantry", pantry: true },
      { n: "Dijon mustard", q: "1 tsp", s: "pantry", pantry: true },
    ],
    method: [
      "Poach or pan-cook the chicken; rest and slice. Boil eggs 7 minutes.",
      "Build rows of lettuce, tomato, avocado, feta, chicken and halved eggs.",
      "Shake oil, vinegar and mustard into a dressing; pour at the table.",
    ],
    why: "Vinegar in the dressing is the Inchauspé move: acid with a meal blunts the glucose curve, and on a salad it is simply lunch.",
    whySource: "Jessie Inchauspé, Glucose Revolution; small trials on vinegar and postprandial glucose",
  },
  {
    id: "keto-fish-parcels-lc", name: "Fish parcels with fennel and olives", time: 15, total: 30,
    serves: 4, tags: ["keto", "fish", "oven", "quick", "gf", "nosugar"], netCarbs: 4,
    macros: { kcal: 290, protein: 33, fat: 15, carbs: 4, sugars: 3, fibre: 3 },
    ingredients: [
      { n: "White fish fillets", q: "4", s: "fishmeat" },
      { n: "Fennel bulb", q: "1", s: "produce" },
      { n: "Cherry tomatoes", q: "200 g", s: "produce" },
      { n: "Kalamata olives", q: "100 g", s: "pantry" },
      { n: "Lemon", q: "1", s: "produce" },
      { n: "Olive oil", q: "3 tbsp", s: "pantry", pantry: true },
    ],
    method: [
      "Heat the oven to 200°C. Lay each fillet on baking paper with shaved fennel, tomatoes and olives.",
      "Dress with oil, lemon and pepper; fold into sealed parcels.",
      "Bake 15 minutes. Open at the table for the steam moment.",
    ],
    why: "Parcels make white fish forgiving, and this plate is Mediterranean and ketogenic at the same time, which is the point: the patterns share more than they argue.",
    whySource: "Australian Dietary Guidelines; PREDIMED",
  },
  // ---------- breakfasts ----------
  {
    id: "bf-overnight-oats", name: "Overnight oats with berries and seeds", time: 5, total: 5,
    serves: 2, tags: ["breakfast", "veg", "nosugar", "quick", "kidsafe"],
    macros: { kcal: 340, protein: 12, fat: 10, carbs: 48, sugars: 9, fibre: 8 },
    ingredients: [
      { n: "Rolled oats", q: "1 cup", s: "pantry" },
      { n: "Milk or kefir", q: "1.5 cups", s: "fridge" },
      { n: "Frozen berries", q: "1 cup", s: "frozen" },
      { n: "Chia or linseeds", q: "2 tbsp", s: "pantry", pantry: true },
      { n: "Greek yoghurt", q: "1/2 cup", s: "fridge" },
    ],
    method: ["Stir oats, milk and seeds in a jar the night before.", "Morning: top with yoghurt and berries. Done before the kettle boils."],
    why: "Oats and seeds carry soluble fibre that steadies morning glucose and feeds the microbiome; the fridge does the cooking.",
    whySource: "Beta-glucan evidence (EFSA approved claim); Australian Dietary Guidelines",
  },
  {
    id: "bf-savoury-eggs", name: "Savoury breakfast: eggs, greens and tomato", time: 10, total: 10,
    serves: 2, tags: ["breakfast", "veg", "keto", "gf", "nosugar", "quick"], netCarbs: 4,
    macros: { kcal: 290, protein: 17, fat: 22, carbs: 4, sugars: 3, fibre: 2 },
    ingredients: [
      { n: "Eggs", q: "4", s: "fridge" },
      { n: "Baby spinach", q: "100 g", s: "produce" },
      { n: "Cherry tomatoes", q: "150 g", s: "produce" },
      { n: "Olive oil", q: "1 tbsp", s: "pantry", pantry: true },
    ],
    method: ["Wilt spinach and halved tomatoes in oil, two minutes.", "Push aside, fry or scramble the eggs. Salt, pepper, plates."],
    why: "The savoury-first breakfast is the single most repeated glucose hack: protein and fat first flattens the whole morning's curve.",
    whySource: "Inchauspé, Glucose Revolution (2022); postprandial studies",
  },
  {
    id: "bf-yoghurt-nuts", name: "Greek yoghurt, nuts and fruit", time: 3, total: 3,
    serves: 1, tags: ["breakfast", "veg", "gf", "nosugar", "quick", "kidsafe"],
    macros: { kcal: 320, protein: 18, fat: 18, carbs: 20, sugars: 16, fibre: 4 },
    ingredients: [
      { n: "Greek yoghurt", q: "1 cup", s: "fridge" },
      { n: "Mixed nuts", q: "30 g", s: "pantry", pantry: true },
      { n: "Seasonal fruit", q: "1 piece", s: "produce" },
    ],
    method: ["Bowl, yoghurt, chopped fruit, nuts on top. Three minutes, no cooking."],
    why: "Fermented dairy, nuts and whole fruit: three of the most consistently protective foods in the literature, in one bowl.",
    whySource: "PREDIMED (nuts); WCRF; fermented dairy cohort evidence",
  },
  {
    id: "bf-mamaliga-egg", name: "Warm polenta bowl with egg and cheese", time: 15, total: 15,
    serves: 2, tags: ["breakfast", "veg", "gf", "nosugar", "romanian", "kidsafe"],
    macros: { kcal: 380, protein: 16, fat: 16, carbs: 42, sugars: 2, fibre: 3 },
    ingredients: [
      { n: "Polenta", q: "1/2 cup", s: "pantry" },
      { n: "Eggs", q: "2", s: "fridge" },
      { n: "Telemea or feta", q: "60 g", s: "fridge" },
      { n: "Butter", q: "15 g", s: "fridge" },
    ],
    method: ["Whisk polenta into two cups of simmering water, ten minutes.", "Top with a soft egg, crumbled cheese and a little butter. Winter mornings, solved."],
    why: "Comfort from home that still balances: wholegrain corn, egg protein and cheese. Warm breakfasts keep rushed mornings human.",
    whySource: "Australian Dietary Guidelines",
  },
  // ---------- lunches ----------
  {
    id: "lunch-tuna-beans", name: "Tuna, white bean and lemon salad", time: 10, total: 10,
    serves: 2, tags: ["lunch", "fish", "gf", "nosugar", "quick"],
    macros: { kcal: 380, protein: 30, fat: 16, carbs: 24, sugars: 3, fibre: 8 },
    ingredients: [
      { n: "Tinned tuna in oil", q: "185 g", s: "pantry" },
      { n: "Cannellini beans, tinned", q: "400 g", s: "pantry" },
      { n: "Red onion", q: "1/2", s: "produce" },
      { n: "Parsley", q: "1/2 bunch", s: "produce" },
      { n: "Lemon", q: "1", s: "produce" },
      { n: "Olive oil", q: "2 tbsp", s: "pantry", pantry: true },
    ],
    method: ["Drain tuna and beans into a bowl.", "Add sliced onion, parsley, lemon and oil. Ten minutes, mostly opening tins."],
    why: "Fish and legumes in the same bowl: the two foods the long-life literature agrees on most, from the pantry shelf.",
    whySource: "PREDIMED; legume cohort evidence",
  },
  {
    id: "lunch-leftover-bowl", name: "The leftover bowl, made deliberate", time: 5, total: 5,
    serves: 1, tags: ["lunch", "quick", "nosugar"],
    macros: { kcal: 450, protein: 22, fat: 16, carbs: 50, sugars: 6, fibre: 7 },
    ingredients: [
      { n: "Last night's dinner", q: "1 portion", s: "fridge" },
      { n: "Baby spinach", q: "1 handful", s: "produce" },
      { n: "Lemon or vinegar", q: "a squeeze", s: "pantry", pantry: true },
    ],
    method: ["Reheat last night's dinner, drop it on a handful of leaves, sharpen with lemon.", "Cooking once and eating twice is the whole strategy."],
    why: "The cheapest, most reliable healthy lunch in existence is dinner cooked once more on purpose.",
    whySource: "Meal-planning adherence literature",
  },
  {
    id: "lunch-egg-plate", name: "Egg, avocado and feta plate", time: 8, total: 8,
    serves: 1, tags: ["lunch", "veg", "keto", "gf", "nosugar", "quick"], netCarbs: 5,
    macros: { kcal: 420, protein: 19, fat: 34, carbs: 5, sugars: 2, fibre: 6 },
    ingredients: [
      { n: "Eggs", q: "2", s: "fridge" },
      { n: "Avocado", q: "1", s: "produce" },
      { n: "Feta", q: "40 g", s: "fridge" },
      { n: "Cucumber", q: "1/2", s: "produce" },
      { n: "Olive oil", q: "1 tbsp", s: "pantry", pantry: true },
    ],
    method: ["Boil the eggs seven minutes. Slice avocado and cucumber, crumble the feta.", "Arrange, oil, salt, pepper. A keto lunch that feels like a café."],
    why: "Protein and good fats, almost no carbs: the afternoon stays level and the three-o'clock biscuit loses its argument.",
    whySource: "Satiety literature; ketogenic practice",
  },
  {
    id: "lunch-lentil-soup", name: "Red lentil and carrot soup cup", time: 10, total: 25,
    serves: 4, tags: ["lunch", "vegan", "gf", "nosugar", "batch", "kidsafe"],
    macros: { kcal: 240, protein: 12, fat: 6, carbs: 32, sugars: 6, fibre: 8 },
    ingredients: [
      { n: "Red lentils", q: "1 cup", s: "pantry" },
      { n: "Carrots", q: "2", s: "produce" },
      { n: "Onion", q: "1", s: "produce" },
      { n: "Ground cumin", q: "1 tsp", s: "pantry", pantry: true },
      { n: "Olive oil", q: "2 tbsp", s: "pantry", pantry: true },
      { n: "Lemon", q: "1", s: "produce" },
    ],
    method: ["Soften onion and grated carrot in oil with cumin.", "Add lentils and a litre of water, simmer twenty minutes, blend or don't.", "Lemon at the end. Freezes in cups for the week."],
    why: "A batch of soup in the fridge is lunch decided four days in advance for about a dollar a bowl.",
    whySource: "Legume evidence (WCRF); budget nutrition practice",
  },
];

// ---------- Learn: the why behind the pattern ----------
// strength: "strong" (consensus guidance) | "emerging" (promising, not settled) | "thin" (popular, weak evidence)

export const WHY_CARDS = [
  {
    id: "variety",
    title: "Vegetable variety beats vegetable virtue",
    oneLiner: "Different plants feed different gut bacteria. Count colours across a week, not grams at a meal.",
    body: "The fibre and phytochemical mix differs from plant to plant, and gut microbiome studies keep finding that people who eat a wider variety of plants host a more diverse microbiome. Practically: a soup with five vegetables does more than a heroic pile of one. Aim for variety across the week and let single meals be ordinary.",
    strength: "strong",
    source: "World Cancer Research Fund; American Gut Project (microbiome diversity)",
    action: "This week's plan already rotates plant families. Notice the variety, not the volume.",
  },
  {
    id: "fibre",
    title: "Fibre is the closest thing food has to a consensus",
    oneLiner: "Higher fibre intake tracks with lower bowel cancer and heart disease risk in study after study.",
    body: "Wholegrains, legumes, vegetables and fruit. The evidence for fibre is about as strong as nutrition evidence gets: consistent across large cohorts and supported by trials on intermediate outcomes. The bowel cancer link is the reason wholegrains and legumes keep appearing in your meal plan.",
    strength: "strong",
    source: "World Cancer Research Fund Continuous Update Project; NHMRC",
    action: "Swap one white staple for its wholegrain version this week. One, not all.",
  },
  {
    id: "fish",
    title: "Fish twice a week is a bet with good odds",
    oneLiner: "Oily fish carries omega-3s the body cannot make well itself.",
    body: "Regular fish eaters show consistently better heart outcomes, and dietary guidelines across countries converge on one to two fish meals a week. Tinned salmon, sardines and tuna count: the tin is how the habit survives a busy week.",
    strength: "strong",
    source: "Heart Foundation (Australia); Australian Dietary Guidelines",
    action: "One fresh fish night plus one tinned-fish backup is the pattern the plan aims at.",
  },
  {
    id: "upf",
    title: "Ultra-processed food: pattern, not panic",
    oneLiner: "High ultra-processed intake tracks with worse outcomes. The fix is displacement, not bans.",
    body: "Large cohort studies link diets high in ultra-processed food with higher risks of cardiovascular disease and some cancers, though untangling cause from correlation is genuinely hard. The practical move is quiet displacement: when whole-food dinners fill the week, the packaged share falls without a single food being forbidden. Forbidding tends to backfire anyway.",
    strength: "emerging",
    source: "BMJ and Lancet cohort analyses of ultra-processed food; WCRF",
    action: "No banned foods here. Cook the plan and the ratio shifts on its own.",
  },
  {
    id: "processed-meat",
    title: "Processed meat is the one to actually limit",
    oneLiner: "Salami, bacon, ham and sausages carry the clearest food-specific cancer signal.",
    body: "The evidence linking processed meat to bowel cancer is strong enough that the WHO classifies it as carcinogenic to humans. Fresh red meat sits in a milder category: the guidance is moderation, around three serves a week. This is the one place where a specific food, rather than a pattern, deserves the attention.",
    strength: "strong",
    source: "IARC/WHO classification; World Cancer Research Fund",
    action: "Deli meats become the occasional guest, not the default sandwich.",
  },
  {
    id: "alcohol",
    title: "Alcohol: the honest version",
    oneLiner: "For cancer risk specifically, the research found no safe threshold. What you do with that is your choice.",
    body: "The cardio-protective story about moderate drinking has largely collapsed under better methods, and for several cancers the risk rises from low levels. This is not an instruction to abstain; it is the real map. Know first, then choose: some people will keep the Friday glass and own the small risk, and that is a legitimate, informed decision.",
    strength: "strong",
    source: "WHO statement on alcohol and health (2023); Cancer Council Australia",
    action: "If you want a lever: alcohol-free days are easier to keep than smaller pours.",
  },
  {
    id: "movement",
    title: "150 to 300 minutes, counted kindly",
    oneLiner: "Brisk walking counts. Playing with your kids counts. The dose window is wide and forgiving.",
    body: "The global guideline is 150 to 300 minutes of moderate activity a week plus two strength sessions, and the risk curves show the steepest benefit right at the start: going from nothing to something matters more than going from good to heroic. Movement also carries its own cancer-prevention signal, independent of anything on the plate.",
    strength: "strong",
    source: "WHO Physical Activity Guidelines (2020); WCRF",
    action: "Protect the walk that already survives your real week. Growth comes after reliability.",
  },
  {
    id: "strength-training",
    title: "Muscle is a health organ",
    oneLiner: "Two short strength sessions a week is the most under-rated line in the guidelines.",
    body: "Strength work improves glucose handling, bone density and, in older age, independence. It is also the guideline line most people skip. A session can be fifteen minutes with a resistance band or your own body weight; the bar for benefit is far lower than gym culture suggests.",
    strength: "strong",
    source: "WHO Physical Activity Guidelines (2020)",
    action: "Two fifteen-minute sessions beat one imaginary hour. Put them next to something you already do.",
  },
  {
    id: "sleep",
    title: "Sleep is upstream of everything else",
    oneLiner: "Short sleep pushes appetite, mood and blood sugar in the wrong direction within days.",
    body: "Adults function best on seven to nine hours. Experimental studies show that even a few short nights shift hunger hormones and glucose tolerance, which is why willpower fails on tired weeks: the deck is stacked. The pattern to protect is a consistent wind-down and wake time; perfect nights are not the goal.",
    strength: "strong",
    source: "Sleep Health Foundation (Australia); experimental sleep-restriction studies",
    action: "Pick a wind-down cue you can keep on the worst weeknight, not the best one.",
  },
  {
    id: "hydration",
    title: "Water as the default drink",
    oneLiner: "Most of hydration's benefit comes from what the water replaces.",
    body: "Plain water displaces sugary drinks, and that displacement, not any detox magic, is where the health effect lives. Thirst is a reasonable guide for most people. The habit worth building is structural: a full water bottle where you can see it.",
    strength: "strong",
    source: "Australian Dietary Guidelines",
    action: "One visible bottle, refilled at lunch. That is the whole system.",
  },
  {
    id: "anti-inflammatory",
    title: "About the phrase 'anti-inflammatory diet'",
    oneLiner: "The pattern is real; the branding oversells it.",
    body: "No single food switches inflammation off, and most 'anti-inflammatory' product claims are marketing. What is true: the whole pattern this app plans, vegetables, olive oil, fish, nuts, legumes, wholegrains, is associated with lower inflammatory markers in trials like PREDIMED. Trust the pattern, ignore the superfood of the month.",
    strength: "emerging",
    source: "PREDIMED trial; reviews of dietary patterns and inflammatory markers",
    action: "When a headline says one food fights inflammation, read it as: the pattern matters, this food is fine.",
  },
  {
    id: "supplements",
    title: "Supplements: food first, honestly",
    oneLiner: "For most well-fed people, supplements have repeatedly failed to beat food.",
    body: "Large trials of vitamin supplements for cancer and heart prevention have mostly come back neutral, and a few came back harmful. Real deficiencies exist and get diagnosed by doctors with blood tests, which is exactly the point: supplementation is a medical conversation, not a shopping decision. This app will never recommend one.",
    strength: "strong",
    source: "USPSTF reviews; Cancer Council Australia",
    action: "Curious whether you need something? That question belongs in your GP question list, and this app will happily help you write it down.",
  },
  {
    id: "weight-free",
    title: "Why this app never asks about weight",
    oneLiner: "Behaviour is the input you control. Energy is the feedback that keeps you honest and kind.",
    body: "Weight is the noisiest signal in daily health: it moves with salt, sleep, hormones and time of day, and tracking it daily reliably lowers mood without improving behaviour. The behaviours this app tracks, what you eat, how you move, how you sleep, are the actual levers, and energy is how progress feels from the inside. If a clinician sets a weight-related goal with you, that conversation belongs with them.",
    strength: "strong",
    source: "Lifestyle-medicine practice; evidence on self-weighing and mood in disordered-eating risk groups",
    action: "Rate your energy each week and watch the trend. It is the honest scoreboard.",
  },
  {
    id: "screening",
    title: "Screening on time is prevention too",
    oneLiner: "The calendar is part of the diet-and-lifestyle story: finding things early changes everything.",
    body: "Lifestyle lowers risk; it never zeroes it. National screening programs (bowel, breast, cervical, and skin checks by risk) exist because early detection changes outcomes dramatically. Keeping those appointments is as much a health behaviour as any dinner in this app, which is why the Care page will nudge you to ask your GP what is due.",
    strength: "strong",
    source: "Australian national screening programs; Cancer Council Australia",
    action: "Open Care and add the next check-up you have been meaning to book.",
  },
];

// ---------- gentle nudges (one active at a time) ----------
export const NUDGES = [
  { id: "walk-after-dinner", habit: "move", text: "A ten-minute walk after dinner, on the nights it fits", why: "Post-meal movement helps blood sugar settle, and ten minutes is small enough to survive real life.", source: "WHO Physical Activity Guidelines" },
  { id: "strength-15", habit: "move", text: "Two fifteen-minute strength sessions, parked next to something you already do", why: "The strength line of the guidelines is the one most people skip, and the benefit threshold is low.", source: "WHO Physical Activity Guidelines" },
  { id: "winddown", habit: "sleep", text: "One wind-down cue at the same time each night", why: "Consistency cues the body better than duration targets. The cue is the habit.", source: "Sleep Health Foundation" },
  { id: "screens-out", habit: "sleep", text: "Phone charges outside the bedroom", why: "Removing the option beats resisting it. Friction is stronger than willpower at 11pm.", source: "Sleep Health Foundation" },
  { id: "veg-at-lunch", habit: "food", text: "Add one vegetable to lunch, the meal that usually goes without", why: "Lunch is where vegetable intake quietly collapses. One addition moves the weekly variety count.", source: "Australian Dietary Guidelines" },
  { id: "legume-swap", habit: "food", text: "One legume meal this week, from the plan", why: "Legumes are the most under-eaten food group with the best evidence behind it.", source: "World Cancer Research Fund" },
  { id: "bottle-visible", habit: "water", text: "A full water bottle on the desk or bench, where you can see it", why: "Visible water gets drunk. The bottle is the system; you are not the system.", source: "Behavioural design research" },
  { id: "afd", habit: "food", text: "Two alcohol-free weekdays, if drinking is part of your week", why: "Alcohol-free days are easier to keep than smaller pours, and the cancer evidence favours fewer drinking occasions.", source: "Cancer Council Australia" },
];

export const HABITS = [
  { id: "move", label: "Moved", question: "Did the body get to move today?", icon: "walk" },
  { id: "sleep", label: "Slept well", question: "Did last night's sleep feel enough?", icon: "moon" },
  { id: "food", label: "Ate well", question: "Did today mostly look like the pattern?", icon: "bowl" },
  { id: "water", label: "Water first", question: "Was water the default drink today?", icon: "drop" },
];
